services:
  - type: web
    name: mon-projet-web
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mon-projet-db
          property: connectionString

databases:
  - name: mon-projet-db
    plan: free
    databaseName: inscription_db
